#Valid actions:
#  - [MESSAGE] - Send a message to the player
#  - [COMMAND] - Execute a command as the player
#  - [CONSOLE] - Send a command as the console
#  - [BROADCAST] - Send a message to all players
#  - [TITLEMSG] - Send a title to the player - add /subtitle for subtitle
#  - [TITLEBROADCAST] - Send a title to all the players - add /subtitle for subtitle
#  - [SOUNDMSG] - Play a sound to the player
#  - [SOUNDBROADCAST] - Play a sound to all the players
#Sounds from https://helpch.at/docs/1.17.1/org/bukkit/Sound.html
#You can use %player% placeholder for the player name
config:
  debug-mode: false
  disable-minecraft-join-message: true
join-actions:
  default:
    priority: 1
    actions:
      - "[MESSAGE] 67%player% &ehas joined the lobby"
    permission: deluxejoin.default
  vip:
    priority: 2
    actions:
      - "[MESSAGE] &a&lVIP &a%player% &ehas joined the lobby"
      - "[SOUNDMSG] BLOCK_ANVIL_PLACE"
      - "[TITLEBROADCAST] &a&lVIP &a%player% /subtitle &ehas joined the lobby"
    permission: deluxejoin.vip

